// Manager: board/pecat, target, sponsor, fans marah, media, insider, akademi, stamina/umur/puas, titipan, wasit sogok
const Manager={confidence:60,fanMood:65,sponsor:100,cash:50,scandal:0,
setTarget(div,idx){this.target=CLUB_TARGETS[div][idx||2];return this.target;},
boardTick(res){if(res==='win')this.confidence+=4;if(res==='draw')this.confidence-=1;if(res==='lose')this.confidence-=5;if(this.scandal>0){this.confidence-=6;this.scandal--;}this.confidence=clamp(this.confidence,0,100);if(this.confidence<15)return'PECAT: board vote out';if(this.confidence<25)return'peringatan keras terakhir';return'aman ('+this.confidence+')';},
sponsorTick(res){if(res==='win')this.sponsor=Math.min(120,this.sponsor+2);if(res==='lose')this.sponsor=Math.max(0,this.sponsor-4);this.cash+=res==='win'?4:(res==='draw'?1:-1);return'sponsor '+this.sponsor+' | kas '+this.cash;},
fanTick(res,derby){if(res==='win')this.fanMood+=derby?8:4;if(res==='lose')this.fanMood-=derby?9:5;this.fanMood=clamp(this.fanMood,0,100);if(this.fanMood<20)return'ANCAMAN: boikot kandang + teror inbox + tuntut mundur';if(this.fanMood<30)return'protes: spanduk + boikot + ancaman';if(this.fanMood<50)return'siul + desak ganti taktik';return'dukungan penuh';},
stadiumIncome(att){const inc=Math.round(att*0.001);this.cash+=inc;return'tiket +'+inc+' | merch +'+Math.round(inc*0.4);},
academyIntake(){const N=['Raka','Dimas','Fajar','Bagas','Yoga','Ilham','Rizky','Andika','Putra','Galih','Bima','Eko'];let o=[];for(let i=0;i<6;i++){const age=14+Math.floor(Math.random()*5);const ovr=clamp(45+Math.floor(Math.random()*20),RATING_MIN,90);const pot=clamp(ovr+5+Math.floor(Math.random()*20),RATING_MIN,POT_MAX);const r=Math.random();o.push({name:N[Math.floor(Math.random()*N.length)]+' U'+age,age,ovr,pot,stam:80+Math.floor(Math.random()*15),mood:65+Math.floor(Math.random()*15),type:r<0.12?'anak legenda':(r<0.2?'titipan sponsor':(r<0.26?'anak artis':'murni'))});}return o;},
ageDecline(age,ovr){if(age<21)return ovr+2;if(age<=30)return ovr;if(age<=33)return ovr-1;return ovr-3;},
satisfaction(minutes,target){return clamp(60+(minutes-target)*0.5,0,100);},
titipanEvent(){const t=['anak legenda minta debut 3 laga','anak sponsor wajib main 5 laga','anak artis minta nomor 10'];const p=t[Math.floor(Math.random()*t.length)];return{TITIPAN:p,efek:'Terima: kas +8, fans -5 jika jelek. Tolak: confidence -6, ruang ganti +5.'};},
refEvent(c){if(c==='sogok'){if(Math.random()<0.35){this.scandal=3;this.confidence=Math.max(0,this.confidence-20);this.sponsor=Math.max(0,this.sponsor-15);return{bias:null,scandal:true,info:'MEDIA UNGKAP: skandal suap! Board -20, sponsor tahan dana, diselidiki 3 laga.'};}return{bias:'home',scandal:false,info:'Wasit condong tuan rumah (risiko diedus media).'};}return{bias:null,scandal:false,info:'Main bersih.'};},
rumor(p){const l=Math.random();if(l<0.5)return'SAMAR: '+p+' dikaitkan pindah...';if(l<0.85)return'Bang R: negosiasi '+p+' tahap akhir.';return'Bang R HERE WE GO! '+p+' deal, tinggal medis.';},
press(choice){if(choice==='sombong'){this.fanMood=clamp(this.fanMood+3,0,100);this.confidence=clamp(this.confidence-2,0,100);return'Fans suka, board tidak suka.';}if(choice==='rendah'){this.confidence=clamp(this.confidence+3,0,100);return'Board suka.';}this.fanMood=clamp(this.fanMood+1,0,100);this.confidence=clamp(this.confidence+1,0,100);return'Aman.';}
};
